name: FitGirl Scraper

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run scraper
        run: bun run index.ts
        env:
          BUN_RUNTIME_OPTIONS: --max-heap-size=4096m
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and push if changes
        run: |
          git config --global user.name 'MohamedBechirMejri'
          git config --global user.email 'mohamed.bechir.mejri.dev@gmail.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update scraped data: $(date)" && git push)
