name: FitGirl Scraper

on:
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run scraper
        run: bun run index.ts
        env:
          BUN_RUNTIME_OPTIONS: --max-heap-size=4096m
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update latest run timestamp
        run: |
            echo "Latest run: $(date -u)" > latest_run_timestamp.txt

      - name: Update latest changes file timestamp
        run: |
          if [ "$(git status --porcelain)" ]; then
            echo "Latest changes: $(date -u)" > latest_changes_timestamp.txt
          fi

      - name: Commit and push if changes
        run: |
          git config --global user.name 'MohamedBechirMejri'
          git config --global user.email 'mohamed.bechir.mejri.dev@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update scraped data: $(date -u)" && git push)
